[project]
name = "SP"
version = "1.0.0"
description = "Machine learning applied to the Spere packing problem in d dimensions"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"